version: '2'
services:
  web:
    image: mental/common:1.0
    container_name: cont_common
    build: .
    ports:
    - "8080:8080"
    links:
      - db
  db:
    image: sameersbn/postgresql
    container_name: cont_common_postgre
    ports:
      - "5432:5432"
    environment:
      - DB_USER=common
      - DB_PASS=common
      - DB_NAME=db_common