version: "3.3"
services:
  web:
    image: mental/common
    build: .
    container_name: mencommon
    ports:
      - "10060:10060"
    links:
      - cont_postgresql
    depends_on:
      - cont_postgresql
    environment:
      SPRING_PROFILES_ACTIVE: qa
  cont_postgresql:
    image: sameersbn/postgresql
    ports:
      - "5432:5432"
    environment:
      DB_NAME: common-dev,common-qa
      DB_USER: dbuser
      DB_PASS: 12345