spring:
  datasource:
    url: jdbc:postgresql://${connection:localhost}:5432/common-dev
    username: dbuser
    password: 12345
  jpa:
    show-sql: true
liquibase:
  drop-first: true
  contexts: default
logging:
  level:
    org.springframework.web: DEBUG
    com.teammental: DEBUG
security.ignored: /**